from PyQt5 import QtCore, QtGui, QtWidgets
from adminLogin import *
from studReg import *
from facultyReg import *


class Ui_AdminDashboard(object):


    def loadStudentData(self):
        connection = sqlite3.connect('cubixUniversity.db')
        cur = connection.cursor()
        sqlstr = 'SELECT * FROM studentCredentials'
        self.tableWidget_3.setRowCount(0)

        results = cur.execute(sqlstr)

        for row_number, row_data in enumerate(results):
            self.tableWidget_3.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget_3.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def loadFacultyData(self):
        connection = sqlite3.connect('cubixUniversity.db')
        cur = connection.cursor()
        sqlstr = 'SELECT * FROM facultyCredentials'
        self.tableWidget.setRowCount(0)

        results = cur.execute(sqlstr)

        for row_number, row_data in enumerate(results):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

        connection.close()

    def openwindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_adminloginscreen()
        self.ui.setupUi(self.window)
        self.window.show()
        AdminDashboard.hide()

    def openfacReg(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_facultyRegistration()
        self.ui.setupUi(self.window)
        self.window.show()

    def openstudReg(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_studentRegistration()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, AdminDashboard):
        AdminDashboard.setObjectName("AdminDashboard")
        AdminDashboard.resize(950, 650)
        AdminDashboard.setStyleSheet("background-color: rgb(0,0,0);")
        self.centralwidget = QtWidgets.QWidget(AdminDashboard)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 321, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "font: 25pt \"Rockwell\";")
        self.label.setObjectName("label")
        self.dock_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.dock_widget.setGeometry(QtCore.QRect(0, 100, 951, 561))
        self.dock_widget.setStyleSheet("background-color: rgb(74, 101, 116);\n"
                                       "font: 12pt \"Rockwell\";")
        self.dock_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.dock_widget.setObjectName("dock_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 761, 501))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.verticalHeader().setDefaultSectionSize(46)
        self.add_Fac = QtWidgets.QPushButton(self.tab)
        self.add_Fac.clicked.connect(self.openfacReg)
        self.add_Fac.setGeometry(QtCore.QRect(790, 40, 121, 51))
        self.add_Fac.setStyleSheet("background-color: rgb(255, 255, 127);\n"
                                   "border-radius: 8px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_Fac.setIcon(icon)
        self.add_Fac.setIconSize(QtCore.QSize(25, 25))
        self.add_Fac.setObjectName("add_Fac")
        self.updateFac = QtWidgets.QPushButton(self.tab)
        self.updateFac.setGeometry(QtCore.QRect(790, 120, 121, 51))
        self.updateFac.setStyleSheet("background-color: rgb(255, 255, 127);\n"
                                     "border-radius: 8px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("update-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateFac.setIcon(icon1)
        self.updateFac.setIconSize(QtCore.QSize(25, 25))
        self.updateFac.setObjectName("updateFac")
        self.del_Fac = QtWidgets.QPushButton(self.tab)
        self.del_Fac.setGeometry(QtCore.QRect(790, 200, 121, 51))
        self.del_Fac.setStyleSheet("background-color: rgb(255, 255, 127);\n"
                                   "border-radius: 8px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_Fac.setIcon(icon2)
        self.del_Fac.setIconSize(QtCore.QSize(25, 25))
        self.del_Fac.setObjectName("del_Fac")
        self.loadFac = QtWidgets.QPushButton(self.tab)

        self.loadFac.setGeometry(QtCore.QRect(790, 270, 121, 51))
        self.loadFac.clicked.connect(self.loadFacultyData)
        self.loadFac.setStyleSheet("background-color: rgb(255, 255, 127);\n"
                                   "border-radius: 8px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("load_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadFac.setIcon(icon3)
        self.loadFac.setIconSize(QtCore.QSize(25, 25))
        self.loadFac.setObjectName("loadFac")
        self.dock_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 10, 761, 501))
        self.tableWidget_3.setStyleSheet("background-color: rgb(162, 255, 255);")
        self.tableWidget_3.setShowGrid(False)
        self.tableWidget_3.setRowCount(20)
        self.tableWidget_3.setColumnCount(10)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(119)
        self.updateStud = QtWidgets.QPushButton(self.tab_2)
        self.updateStud.setGeometry(QtCore.QRect(790, 120, 121, 51))
        self.updateStud.setStyleSheet("background-color: rgb(162, 255, 255);\n"
                                      "border-radius: 8px;")
        self.updateStud.setIcon(icon1)
        self.updateStud.setIconSize(QtCore.QSize(25, 25))
        self.updateStud.setObjectName("updateStud")
        self.delStud = QtWidgets.QPushButton(self.tab_2)
        self.delStud.clicked.connect(self.deleteData)
        self.delStud.clicked.connect(AdminDashboard.close)
        self.delStud.setGeometry(QtCore.QRect(790, 200, 121, 51))
        self.delStud.setStyleSheet("background-color: rgb(162, 255, 255);\n"
                                   "border-radius: 8px;")
        self.delStud.setIcon(icon2)
        self.delStud.setIconSize(QtCore.QSize(25, 25))
        self.delStud.setObjectName("delStud")
        self.addStud = QtWidgets.QPushButton(self.tab_2)
        self.addStud.clicked.connect(self.openstudReg)
        self.addStud.setGeometry(QtCore.QRect(790, 40, 121, 51))
        self.addStud.setStyleSheet("background-color: rgb(162, 255, 255);\n"
                                   "border-radius: 8px;")
        self.addStud.setIcon(icon)
        self.addStud.setIconSize(QtCore.QSize(25, 25))
        self.addStud.setObjectName("addStud")
        self.load_stud = QtWidgets.QPushButton(self.tab_2)
        self.load_stud.clicked.connect(self.loadStudentData)
        self.load_stud.setGeometry(QtCore.QRect(790, 280, 121, 51))
        self.load_stud.setStyleSheet("background-color: rgb(162, 255, 255);\n"
                                     "border-radius: 8px;")
        self.load_stud.setIcon(icon3)
        self.load_stud.setIconSize(QtCore.QSize(25, 25))
        self.load_stud.setObjectName("load_stud")
        self.dock_widget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 10, 771, 501))
        self.tableWidget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_4.setShowGrid(True)
        self.tableWidget_4.setRowCount(20)
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setObjectName("tableWidget_4")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(119)
        self.load_stud_2 = QtWidgets.QPushButton(self.tab_3)
        self.load_stud_2.clicked.connect(self.loadData)
        self.load_stud_2.setGeometry(QtCore.QRect(790, 60, 141, 51))
        self.load_stud_2.setStyleSheet("background-color: rgb(255, 111, 111);\n"
                                       "border-radius: 8px;")
        self.load_stud_2.setIcon(icon3)
        self.load_stud_2.setIconSize(QtCore.QSize(25, 25))
        self.load_stud_2.setObjectName("load_stud_2")
        self.dock_widget.addTab(self.tab_3, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 101, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("admin_photo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.logout_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.logout_pushButton.clicked.connect(self.openwindow)
        self.logout_pushButton.setGeometry(QtCore.QRect(880, 10, 61, 61))
        self.logout_pushButton.setStyleSheet("border: none;\n"
                                             "boder-radius: 25px;")
        self.logout_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_pushButton.setIcon(icon4)
        self.logout_pushButton.setIconSize(QtCore.QSize(60, 70))
        self.logout_pushButton.setObjectName("logout_pushButton")
        AdminDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminDashboard)
        self.dock_widget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(AdminDashboard)

    def retranslateUi(self, AdminDashboard):
        _translate = QtCore.QCoreApplication.translate
        AdminDashboard.setWindowTitle(_translate("AdminDashboard", "Admin Dashboard"))
        self.label.setText(_translate("AdminDashboard", "ADMIN DASHBOARD"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AdminDashboard", "ID No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AdminDashboard", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AdminDashboard", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AdminDashboard", "Address"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AdminDashboard", "Phone No."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("AdminDashboard", "Sex"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("AdminDashboard", "Email"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("AdminDashboard", "Department"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("AdminDashboard", "Username"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("AdminDashboard", "Password"))
        self.add_Fac.setText(_translate("AdminDashboard", "ADD"))
        self.updateFac.setText(_translate("AdminDashboard", "UPDATE"))
        self.del_Fac.setText(_translate("AdminDashboard", "DELETE"))
        self.loadFac.setText(_translate("AdminDashboard", "LOAD"))
        self.dock_widget.setTabText(self.dock_widget.indexOf(self.tab), _translate("AdminDashboard", "Faculty "))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("AdminDashboard", "ID No."))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("AdminDashboard", "First Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("AdminDashboard", "Last Name"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("AdminDashboard", "Address"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("AdminDashboard", "Phone"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("AdminDashboard", "Sex"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("AdminDashboard", "Email"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("AdminDashboard", "Course"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("AdminDashboard", "Username"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("AdminDashboard", "Password"))
        self.updateStud.setText(_translate("AdminDashboard", "UPDATE"))
        self.delStud.setText(_translate("AdminDashboard", "DELETE"))
        self.addStud.setText(_translate("AdminDashboard", "ADD"))
        self.load_stud.setText(_translate("AdminDashboard", "LOAD"))
        self.dock_widget.setTabText(self.dock_widget.indexOf(self.tab_2), _translate("AdminDashboard", "Student"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("AdminDashboard", "ID No."))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("AdminDashboard", "Recipient"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("AdminDashboard", "Date"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("AdminDashboard", "TIme"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("AdminDashboard", "Concern"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("AdminDashboard", "Purpose"))
        self.load_stud_2.setText(_translate("AdminDashboard", "LOAD"))
        self.dock_widget.setTabText(self.dock_widget.indexOf(self.tab_3),
                                    _translate("AdminDashboard", "Student Appointments"))

    def loadData(self):
        connection = sqlite3.connect('cubixUniversity.db')
        cur = connection.cursor()
        sqlstr = 'SELECT * FROM studentAppointments LIMIT 10'

        tablerow = 0
        results = cur.execute(sqlstr)

        for row in results:
            self.tableWidget_4.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[2]))
            self.tableWidget_4.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidget_4.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(row[3]))
            self.tableWidget_4.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(row[4]))
            self.tableWidget_4.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(row[5]))
            self.tableWidget_4.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(row[6]))

            tablerow += 1

    def deleteData(self):
        connection = sqlite3.connect('cubixUniversity.db')
        cursor = connection.cursor()
        content = 'SELECT  * FROM studentCredentials,studentAppointments'
        res = cursor.execute(content)

        for rows in enumerate(res):
            if rows[0] == self.tableWidget.currentRow():
                print(rows[1])

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AdminDashboard = QtWidgets.QMainWindow()
    ui = Ui_AdminDashboard()
    ui.setupUi(AdminDashboard)
    AdminDashboard.show()
    sys.exit(app.exec_())
