from PyQt5 import QtCore, QtGui, QtWidgets
from login_teachers import *
import sqlite3

class Ui_facultyDashboard(object):
    def logout(self):
        self.main_Screen = QtWidgets.QMainWindow()
        self.ui = Ui_main_Screen()
        self.ui.setupUi(self.main_Screen)
        self.main_Screen.show()

    def setupUi(self, facultyDashboard):
        facultyDashboard.setObjectName("facultyDashboard")
        facultyDashboard.resize(950, 662)
        facultyDashboard.setAutoFillBackground(False)
        facultyDashboard.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(facultyDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 491, 51))
        self.label.setStyleSheet("font: 75 28pt \"Rockwell\";\n"
"color: rgb(75, 103, 118);\n"
"background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 80, 241, 31))
        self.label_8.setStyleSheet("font: 75 20pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.appointment = QtWidgets.QTabWidget(self.centralwidget)
        self.appointment.setGeometry(QtCore.QRect(0, 130, 951, 537))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appointment.sizePolicy().hasHeightForWidth())
        self.appointment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.appointment.setFont(font)
        self.appointment.setAutoFillBackground(False)
        self.appointment.setStyleSheet("background-color: rgb(75, 103, 118);")
        self.appointment.setTabPosition(QtWidgets.QTabWidget.North)
        self.appointment.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.appointment.setIconSize(QtCore.QSize(16, 16))
        self.appointment.setElideMode(QtCore.Qt.ElideNone)
        self.appointment.setObjectName("appointment")
        self.myapp = QtWidgets.QWidget()
        self.myapp.setObjectName("myapp")
        self.label_10 = QtWidgets.QLabel(self.myapp)
        self.label_10.setGeometry(QtCore.QRect(350, 20, 271, 41))
        self.label_10.setStyleSheet("font: 75 18pt \"Rockwell\";\n"
"color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.myapp)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(100, 190, 211, 161))
        self.plainTextEdit_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setBackgroundVisible(False)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.myapp)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(590, 190, 211, 161))
        self.plainTextEdit_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_12 = QtWidgets.QLabel(self.myapp)
        self.label_12.setGeometry(QtCore.QRect(100, 140, 211, 51))
        self.label_12.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(255, 170, 0);")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.myapp)
        self.label_14.setGeometry(QtCore.QRect(590, 140, 211, 51))
        self.label_14.setStyleSheet("font: 75 12pt \"Rockwell\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_14.setObjectName("label_14")
        self.upcomingAPpointment = QtWidgets.QLabel(self.myapp)
        self.upcomingAPpointment.setGeometry(QtCore.QRect(340, 140, 221, 51))
        self.upcomingAPpointment.setStyleSheet("font: 75 12pt \"Rockwell\";\n"
"background-color: rgb(255, 170, 127);\n"
"")
        self.upcomingAPpointment.setObjectName("upcomingAPpointment")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.myapp)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(340, 190, 221, 161))
        self.plainTextEdit_5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_19 = QtWidgets.QLabel(self.myapp)
        self.label_19.setGeometry(QtCore.QRect(130, 230, 61, 71))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("past_icon.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.sentApp_num = QtWidgets.QLCDNumber(self.myapp)
        self.sentApp_num.setGeometry(QtCore.QRect(120, 230, 141, 81))
        self.sentApp_num.setStyleSheet("border: 0;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.sentApp_num.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sentApp_num.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sentApp_num.setObjectName("sentApp_num")
        self.label_20 = QtWidgets.QLabel(self.myapp)
        self.label_20.setGeometry(QtCore.QRect(360, 220, 101, 91))
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("alarm clock.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.sentApp_num_2 = QtWidgets.QLCDNumber(self.myapp)
        self.sentApp_num_2.setGeometry(QtCore.QRect(370, 230, 141, 81))
        self.sentApp_num_2.setStyleSheet("border: 0;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.sentApp_num_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sentApp_num_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sentApp_num_2.setObjectName("sentApp_num_2")
        self.sentApp_num_3 = QtWidgets.QLCDNumber(self.myapp)
        self.sentApp_num_3.setGeometry(QtCore.QRect(640, 230, 141, 81))
        self.sentApp_num_3.setStyleSheet("border: 0;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.sentApp_num_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sentApp_num_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sentApp_num_3.setObjectName("sentApp_num_3")
        self.label_21 = QtWidgets.QLabel(self.myapp)
        self.label_21.setGeometry(QtCore.QRect(620, 230, 91, 81))
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("reschedule.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_10.raise_()
        self.plainTextEdit_2.raise_()
        self.plainTextEdit_4.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.plainTextEdit_5.raise_()
        self.upcomingAPpointment.raise_()
        self.sentApp_num.raise_()
        self.label_19.raise_()
        self.sentApp_num_2.raise_()
        self.label_20.raise_()
        self.sentApp_num_3.raise_()
        self.label_21.raise_()
        self.appointment.addTab(self.myapp, "")
        self.setApp = QtWidgets.QWidget()
        self.setApp.setObjectName("setApp")
        self.appointment_2 = QtWidgets.QTableWidget(self.setApp)
        self.appointment_2.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.appointment_2.setStyleSheet("background-color:rgb(118, 164, 186);\n"
"font: 12pt \"Rockwell\";")
        self.appointment_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appointment_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appointment_2.setRowCount(20)
        self.appointment_2.setObjectName("appointment_2")
        self.appointment_2.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.appointment_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.appointment_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.appointment_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.appointment_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.appointment_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.appointment_2.setHorizontalHeaderItem(5, item)
        self.appointment_2.horizontalHeader().setDefaultSectionSize(131)
        self.appointment_2.verticalHeader().setDefaultSectionSize(35)
        self.reschedbtn = QtWidgets.QPushButton(self.setApp)
        self.reschedbtn.setGeometry(QtCore.QRect(810, 330, 121, 41))
        self.reschedbtn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"font: 63 11pt \"Segoe UI Semibold\";")
        self.reschedbtn.setObjectName("reschedbtn")
        self.loadData = QtWidgets.QPushButton(self.setApp)
        self.loadData.clicked.connect(self.loadAppt)
        self.loadData.setGeometry(QtCore.QRect(810, 260, 121, 41))
        self.loadData.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-radius: 15px;\n"
"font: 63 11pt \"Segoe UI Semibold\";")
        self.loadData.setObjectName("loadData")
        self.rejectbtn = QtWidgets.QPushButton(self.setApp)
        self.rejectbtn.setGeometry(QtCore.QRect(810, 190, 121, 41))
        self.rejectbtn.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"border-radius: 15px;\n"
"font: 63 11pt \"Segoe UI Semibold\";")
        self.rejectbtn.setObjectName("rejectbtn")
        self.acceptBtn = QtWidgets.QPushButton(self.setApp)
        self.acceptBtn.setGeometry(QtCore.QRect(810, 120, 121, 41))
        self.acceptBtn.setStyleSheet("background-color: rgb(109, 150, 225);\n"
"font: 63 11pt \"Segoe UI Semibold\";\n"
"border-radius: 15px;")
        self.acceptBtn.setAutoDefault(False)
        self.acceptBtn.setObjectName("acceptBtn")
        self.appointment.addTab(self.setApp, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.dataTable = QtWidgets.QTableWidget(self.tab)
        self.dataTable.setGeometry(QtCore.QRect(0, 0, 791, 501))
        self.dataTable.setStyleSheet("font: 12pt \"Rockwell\";\n"
"background-color: rgb(170, 255, 127);")
        self.dataTable.setRowCount(15)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(5, item)
        self.dataTable.horizontalHeader().setDefaultSectionSize(153)
        self.dataTable.verticalHeader().setDefaultSectionSize(40)
        self.skip = QtWidgets.QPushButton(self.tab)
        self.skip.setGeometry(QtCore.QRect(800, 40, 131, 41))
        self.skip.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius: 15px;\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.skip.setObjectName("skip")
        self.viewBtn_4 = QtWidgets.QPushButton(self.tab)
        self.viewBtn_4.clicked.connect(self.viewAppt)
        self.viewBtn_4.setGeometry(QtCore.QRect(800, 100, 131, 41))
        self.viewBtn_4.setStyleSheet("background-color: rgb(249, 255, 119);\n"
"border-radius: 15px;\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.viewBtn_4.setObjectName("viewBtn_4")
        self.appointment.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.tableWidget.setStyleSheet("font: 14pt \"Rockwell\";\n"
"background-color: rgb(234, 255, 243);")
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(10)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(5)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.deletebtn = QtWidgets.QPushButton(self.tab_2)
        self.deletebtn.clicked.connect(self.deleteData)
        self.deletebtn.setGeometry(QtCore.QRect(820, 110, 111, 51))
        self.deletebtn.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"font: 63 11pt \"Segoe UI Semibold\";\n"
"border-radius: 15px;")
        self.deletebtn.setObjectName("deletebtn")
        self.updatebtn = QtWidgets.QPushButton(self.tab_2)
        self.updatebtn.setGeometry(QtCore.QRect(820, 40, 111, 51))
        self.updatebtn.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 63 11pt \"Segoe UI Semibold\";\n"
"border-radius: 15px;")
        self.updatebtn.setObjectName("updatebtn")
        self.view = QtWidgets.QPushButton(self.tab_2)
        self.view.clicked.connect(self.timeslot)
        self.view.setGeometry(QtCore.QRect(820, 180, 111, 51))
        self.view.setStyleSheet("background-color: rgb(135, 229, 255);\n"
"font: 63 11pt \"Segoe UI Semibold\";\n"
"border-radius: 15px;")
        self.view.setObjectName("view")
        self.appointment.addTab(self.tab_2, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 950, 661))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("facultydashboard_bg.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.logout)
        self.pushButton.setGeometry(QtCore.QRect(880, 10, 61, 61))
        self.pushButton.setStyleSheet("border: none;\n"
"border-radius: 25px;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(60, 70))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("faculty_icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.appointment.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        facultyDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(facultyDashboard)
        self.appointment.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(facultyDashboard)

    def retranslateUi(self, facultyDashboard):
        _translate = QtCore.QCoreApplication.translate
        facultyDashboard.setWindowTitle(_translate("facultyDashboard", "Faculty Dashboard"))
        self.label.setText(_translate("facultyDashboard", "Queue Management System"))
        self.label_8.setText(_translate("facultyDashboard", "Faculty Dashboard"))
        self.label_10.setText(_translate("facultyDashboard", "APPOINTMENT STATUS"))
        self.label_12.setText(_translate("facultyDashboard", "Today\'s Appointments"))
        self.label_14.setText(_translate("facultyDashboard", "Rescheduled Appointments"))
        self.upcomingAPpointment.setText(_translate("facultyDashboard", "Upcoming Appointments"))
        self.appointment.setTabText(self.appointment.indexOf(self.myapp), _translate("facultyDashboard", "My Appointments"))
        item = self.appointment_2.horizontalHeaderItem(0)
        item.setText(_translate("facultyDashboard", "ID No."))
        item = self.appointment_2.horizontalHeaderItem(1)
        item.setText(_translate("facultyDashboard", "Student\'s Name"))
        item = self.appointment_2.horizontalHeaderItem(2)
        item.setText(_translate("facultyDashboard", "Appt Date"))
        item = self.appointment_2.horizontalHeaderItem(3)
        item.setText(_translate("facultyDashboard", "Appt Time"))
        item = self.appointment_2.horizontalHeaderItem(4)
        item.setText(_translate("facultyDashboard", "Concern"))
        item = self.appointment_2.horizontalHeaderItem(5)
        item.setText(_translate("facultyDashboard", "Purpose"))
        self.reschedbtn.setText(_translate("facultyDashboard", "RESCHEDULE"))
        self.loadData.setText(_translate("facultyDashboard", "VIEW"))
        self.rejectbtn.setText(_translate("facultyDashboard", "REJECT"))
        self.acceptBtn.setText(_translate("facultyDashboard", "ACCEPT"))
        self.appointment.setTabText(self.appointment.indexOf(self.setApp), _translate("facultyDashboard", "View  Appointment"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("facultyDashboard", "ID Number"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("facultyDashboard", "First Name"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("facultyDashboard", "Last Name"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("facultyDashboard", "Appointment No."))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("facultyDashboard", "Appt. Date"))
        item = self.dataTable.horizontalHeaderItem(5)
        item.setText(_translate("facultyDashboard", "Appt. Time"))
        self.skip.setText(_translate("facultyDashboard", "SKIP STUDENT"))
        self.viewBtn_4.setText(_translate("facultyDashboard", "VIEW DATA"))
        self.appointment.setTabText(self.appointment.indexOf(self.tab), _translate("facultyDashboard", "Skip Student"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("facultyDashboard", "Student Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("facultyDashboard", "ID Number"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("facultyDashboard", "Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("facultyDashboard", "Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("facultyDashboard", "Availability"))
        self.deletebtn.setText(_translate("facultyDashboard", "DELETE"))
        self.updatebtn.setText(_translate("facultyDashboard", "UPDATE"))
        self.view.setText(_translate("facultyDashboard", "SHOW"))
        self.appointment.setTabText(self.appointment.indexOf(self.tab_2), _translate("facultyDashboard", "View/Edit Timeslot"))

    def loadAppt(self):

            connection = sqlite3.connect('cubixUniversity.db')
            cursor = connection.cursor()
            sql = 'SELECT studentCredentials.ID_Number, studentCredentials.lname, studentAppointments.date, studentAppointments.time, studentAppointments.concern, studentAppointments.purpose FROM studentCredentials,studentAppointments'

            results = cursor.execute(sql)

            for row_number, row_data in enumerate(results):
                self.appointment_2.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.appointment_2.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def viewAppt(self):

            connection = sqlite3.connect('cubixUniversity.db')
            cursor = connection.cursor()
            sql = 'SELECT studentCredentials.ID_Number, studentCredentials.fname,studentCredentials.lname, studentAppointments.AppointmentID,studentAppointments.date, studentAppointments.time FROM studentCredentials,studentAppointments'

            results = cursor.execute(sql)

            for row_number, row_data in enumerate(results):
                self.dataTable.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.dataTable.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def timeslot(self):

        connection = sqlite3.connect('cubixUniversity.db')
        cursor = connection.cursor()
        sql = 'SELECT studentCredentials.ID_Number,studentCredentials.lname, studentAppointments.date, studentAppointments.time FROM studentCredentials,studentAppointments'

        results = cursor.execute(sql)

        for row_number, row_data in enumerate(results):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def deleteData(self):
        connection = sqlite3.connect('cubixUniversity.db')
        cursor = connection.cursor()
        content = 'SELECT  studentCredentials.ID_Number,studentCredentials.lname, studentAppointments.date, studentAppointments.time FROM studentCredentials,studentAppointments'
        res = cursor.execute(content)

        for rows in enumerate(res):
                if rows[0] == self.tableWidget.currentRow():
                    print(rows[1])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    facultyDashboard = QtWidgets.QMainWindow()
    ui = Ui_facultyDashboard()
    ui.setupUi(facultyDashboard)
    facultyDashboard.show()
    sys.exit(app.exec_())
