from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_skip_student(object):
    def setupUi(self, skip_student):
        skip_student.setObjectName("skip_student")
        skip_student.resize(950, 650)
        skip_student.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(skip_student)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 63 20pt \"Segoe UI Semibold\";")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.viewBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.viewBtn_3.setGeometry(QtCore.QRect(140, 600, 191, 41))
        self.viewBtn_3.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius: 15px;\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.viewBtn_3.setObjectName("viewBtn_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(-50, 0, 1001, 651))
        self.label_10.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("facultydashboard_bg.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 20, 951, 41))
        self.label_9.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.viewBtn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.viewBtn_4.setGeometry(QtCore.QRect(760, 600, 161, 41))
        self.viewBtn_4.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius: 15px;\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.viewBtn_4.setObjectName("viewBtn_4")
        self.dataTable = QtWidgets.QTableWidget(self.centralwidget)
        self.dataTable.setGeometry(QtCore.QRect(0, 70, 951, 521))
        self.dataTable.setStyleSheet("font: 12pt \"Rockwell\";")
        self.dataTable.setRowCount(15)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(5, item)
        self.dataTable.horizontalHeader().setDefaultSectionSize(153)
        self.dataTable.verticalHeader().setDefaultSectionSize(40)
        self.viewBtn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.viewBtn_5.setGeometry(QtCore.QRect(410, 600, 191, 41))
        self.viewBtn_5.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.viewBtn_5.setObjectName("viewBtn_5")
        self.label_10.raise_()
        self.label_9.raise_()
        self.label_4.raise_()
        self.viewBtn_3.raise_()
        self.viewBtn_4.raise_()
        self.dataTable.raise_()
        self.viewBtn_5.raise_()
        skip_student.setCentralWidget(self.centralwidget)

        self.retranslateUi(skip_student)
        QtCore.QMetaObject.connectSlotsByName(skip_student)

    def retranslateUi(self, skip_student):
        _translate = QtCore.QCoreApplication.translate
        skip_student.setWindowTitle(_translate("skip_student", "Skip Student"))
        self.label_4.setText(_translate("skip_student", "SKIP STUDENTS"))
        self.viewBtn_3.setText(_translate("skip_student", "SKIP STUDENT"))
        self.viewBtn_4.setText(_translate("skip_student", "BACK"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("skip_student", "ID Number"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("skip_student", "First Name"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("skip_student", "Last Name"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("skip_student", "Appointment No."))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("skip_student", "Appt. Date"))
        item = self.dataTable.horizontalHeaderItem(5)
        item.setText(_translate("skip_student", "Appt. Time"))
        self.viewBtn_5.setText(_translate("skip_student", "SHOW DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    skip_student = QtWidgets.QMainWindow()
    ui = Ui_skip_student()
    ui.setupUi(skip_student)
    skip_student.show()
    sys.exit(app.exec_())
